import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Provider } from 'react-redux'
import { store } from '@/redux/store/store'
import { Providers } from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TremorGuard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar/>
          <main className='flex min-h-screen flex-col items-center justify-between p-24'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
